##########################################################################
# Destroy stage
###########################################################################


destroy:
  stage: destroy
  image: hashicorp/terraform:1.6.6
  script:
    - terraform init
    - terraform destroy -auto-approve
  when: manual
  allow_failure: false
